/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar.tables.records;


import io.ceze.einar.tables.Negotiation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NegotiationRecord extends UpdatableRecordImpl<NegotiationRecord> implements Record3<Integer, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.negotiation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.negotiation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.negotiation.completed</code>.
     */
    public void setCompleted(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.negotiation.completed</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.negotiation.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.negotiation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Boolean, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Boolean, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Negotiation.NEGOTIATION.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Negotiation.NEGOTIATION.COMPLETED;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Negotiation.NEGOTIATION.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getCompleted();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getCompleted();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public NegotiationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NegotiationRecord value2(Boolean value) {
        setCompleted(value);
        return this;
    }

    @Override
    public NegotiationRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NegotiationRecord values(Integer value1, Boolean value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NegotiationRecord
     */
    public NegotiationRecord() {
        super(Negotiation.NEGOTIATION);
    }

    /**
     * Create a detached, initialised NegotiationRecord
     */
    public NegotiationRecord(Integer id, Boolean completed, LocalDateTime createdAt) {
        super(Negotiation.NEGOTIATION);

        setId(id);
        setCompleted(completed);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
