/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar.tables.records;


import io.ceze.einar.tables.Profiles;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilesRecord extends UpdatableRecordImpl<ProfilesRecord> implements Record13<Long, Long, String, String, LocalDate, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.profiles.profile_id</code>.
     */
    public void setProfileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.profiles.profile_id</code>.
     */
    public Long getProfileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.profiles.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.profiles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.profiles.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.profiles.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.profiles.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.profiles.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.profiles.dob</code>.
     */
    public void setDob(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.profiles.dob</code>.
     */
    public LocalDate getDob() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.profiles.street_no</code>.
     */
    public void setStreetNo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.profiles.street_no</code>.
     */
    public Integer getStreetNo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.profiles.street_name</code>.
     */
    public void setStreetName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.profiles.street_name</code>.
     */
    public String getStreetName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.profiles.city</code>.
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.profiles.city</code>.
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.profiles.state</code>.
     */
    public void setState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.profiles.state</code>.
     */
    public String getState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.profiles.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.profiles.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.profiles.country</code>.
     */
    public void setCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.profiles.country</code>.
     */
    public String getCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.profiles.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.profiles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.profiles.last_modified</code>.
     */
    public void setLastModified(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.profiles.last_modified</code>.
     */
    public LocalDateTime getLastModified() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, String, String, LocalDate, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Long, String, String, LocalDate, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Profiles.PROFILES.PROFILE_ID;
    }

    @Override
    public Field<Long> field2() {
        return Profiles.PROFILES.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Profiles.PROFILES.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Profiles.PROFILES.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field5() {
        return Profiles.PROFILES.DOB;
    }

    @Override
    public Field<Integer> field6() {
        return Profiles.PROFILES.STREET_NO;
    }

    @Override
    public Field<String> field7() {
        return Profiles.PROFILES.STREET_NAME;
    }

    @Override
    public Field<String> field8() {
        return Profiles.PROFILES.CITY;
    }

    @Override
    public Field<String> field9() {
        return Profiles.PROFILES.STATE;
    }

    @Override
    public Field<String> field10() {
        return Profiles.PROFILES.POSTAL_CODE;
    }

    @Override
    public Field<String> field11() {
        return Profiles.PROFILES.COUNTRY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Profiles.PROFILES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Profiles.PROFILES.LAST_MODIFIED;
    }

    @Override
    public Long component1() {
        return getProfileId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public LocalDate component5() {
        return getDob();
    }

    @Override
    public Integer component6() {
        return getStreetNo();
    }

    @Override
    public String component7() {
        return getStreetName();
    }

    @Override
    public String component8() {
        return getCity();
    }

    @Override
    public String component9() {
        return getState();
    }

    @Override
    public String component10() {
        return getPostalCode();
    }

    @Override
    public String component11() {
        return getCountry();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component13() {
        return getLastModified();
    }

    @Override
    public Long value1() {
        return getProfileId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public LocalDate value5() {
        return getDob();
    }

    @Override
    public Integer value6() {
        return getStreetNo();
    }

    @Override
    public String value7() {
        return getStreetName();
    }

    @Override
    public String value8() {
        return getCity();
    }

    @Override
    public String value9() {
        return getState();
    }

    @Override
    public String value10() {
        return getPostalCode();
    }

    @Override
    public String value11() {
        return getCountry();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value13() {
        return getLastModified();
    }

    @Override
    public ProfilesRecord value1(Long value) {
        setProfileId(value);
        return this;
    }

    @Override
    public ProfilesRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ProfilesRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ProfilesRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ProfilesRecord value5(LocalDate value) {
        setDob(value);
        return this;
    }

    @Override
    public ProfilesRecord value6(Integer value) {
        setStreetNo(value);
        return this;
    }

    @Override
    public ProfilesRecord value7(String value) {
        setStreetName(value);
        return this;
    }

    @Override
    public ProfilesRecord value8(String value) {
        setCity(value);
        return this;
    }

    @Override
    public ProfilesRecord value9(String value) {
        setState(value);
        return this;
    }

    @Override
    public ProfilesRecord value10(String value) {
        setPostalCode(value);
        return this;
    }

    @Override
    public ProfilesRecord value11(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public ProfilesRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProfilesRecord value13(LocalDateTime value) {
        setLastModified(value);
        return this;
    }

    @Override
    public ProfilesRecord values(Long value1, Long value2, String value3, String value4, LocalDate value5, Integer value6, String value7, String value8, String value9, String value10, String value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfilesRecord
     */
    public ProfilesRecord() {
        super(Profiles.PROFILES);
    }

    /**
     * Create a detached, initialised ProfilesRecord
     */
    public ProfilesRecord(Long profileId, Long userId, String firstName, String lastName, LocalDate dob, Integer streetNo, String streetName, String city, String state, String postalCode, String country, LocalDateTime createdAt, LocalDateTime lastModified) {
        super(Profiles.PROFILES);

        setProfileId(profileId);
        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setDob(dob);
        setStreetNo(streetNo);
        setStreetName(streetName);
        setCity(city);
        setState(state);
        setPostalCode(postalCode);
        setCountry(country);
        setCreatedAt(createdAt);
        setLastModified(lastModified);
        resetChangedOnNotNull();
    }
}
