/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar.tables.records;


import io.ceze.einar.tables.Spaces;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpacesRecord extends UpdatableRecordImpl<SpacesRecord> implements Record5<Long, Long, Long, String, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spaces.space_id</code>.
     */
    public void setSpaceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spaces.space_id</code>.
     */
    public Long getSpaceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.spaces.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spaces.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.spaces.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spaces.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.spaces.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spaces.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.spaces.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spaces.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, String, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Spaces.SPACES.SPACE_ID;
    }

    @Override
    public Field<Long> field2() {
        return Spaces.SPACES.CREATED_BY;
    }

    @Override
    public Field<Long> field3() {
        return Spaces.SPACES.LOCATION_ID;
    }

    @Override
    public Field<String> field4() {
        return Spaces.SPACES.DESCRIPTION;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Spaces.SPACES.PRICE;
    }

    @Override
    public Long component1() {
        return getSpaceId();
    }

    @Override
    public Long component2() {
        return getCreatedBy();
    }

    @Override
    public Long component3() {
        return getLocationId();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    @Override
    public Long value1() {
        return getSpaceId();
    }

    @Override
    public Long value2() {
        return getCreatedBy();
    }

    @Override
    public Long value3() {
        return getLocationId();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    @Override
    public SpacesRecord value1(Long value) {
        setSpaceId(value);
        return this;
    }

    @Override
    public SpacesRecord value2(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SpacesRecord value3(Long value) {
        setLocationId(value);
        return this;
    }

    @Override
    public SpacesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SpacesRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public SpacesRecord values(Long value1, Long value2, Long value3, String value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpacesRecord
     */
    public SpacesRecord() {
        super(Spaces.SPACES);
    }

    /**
     * Create a detached, initialised SpacesRecord
     */
    public SpacesRecord(Long spaceId, Long createdBy, Long locationId, String description, BigDecimal price) {
        super(Spaces.SPACES);

        setSpaceId(spaceId);
        setCreatedBy(createdBy);
        setLocationId(locationId);
        setDescription(description);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
