/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.Customers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record7<Long, String, String, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customers.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customers.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.customers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customers.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customers.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customers.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customers.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.customers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.customers.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customers.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.customers.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.customers.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Customers.CUSTOMERS.CUSTOMER_ID;
    }

    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Customers.CUSTOMERS.PHONE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Customers.CUSTOMERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Customers.CUSTOMERS.LAST_UPDATED;
    }

    @Override
    public Field<Integer> field7() {
        return Customers.CUSTOMERS.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getCustomerId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdated();
    }

    @Override
    public Integer component7() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getCustomerId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdated();
    }

    @Override
    public Integer value7() {
        return getTenantId();
    }

    @Override
    public CustomersRecord value1(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CustomersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomersRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public CustomersRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CustomersRecord value6(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public CustomersRecord value7(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public CustomersRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Long customerId, String name, String email, String phone, LocalDateTime createdAt, LocalDateTime lastUpdated, Integer tenantId) {
        super(Customers.CUSTOMERS);

        setCustomerId(customerId);
        setName(name);
        setEmail(email);
        setPhone(phone);
        setCreatedAt(createdAt);
        setLastUpdated(lastUpdated);
        setTenantId(tenantId);
        resetChangedOnNotNull();
    }
}
