/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.enums.State;
import com.maelstrom.jooq.tables.Inventories;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoriesRecord extends UpdatableRecordImpl<InventoriesRecord> implements Record8<Integer, String, Integer, String, State, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.inventories.inventory_id</code>.
     */
    public void setInventoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.inventories.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.inventories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.inventories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.inventories.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.inventories.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.inventories.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.inventories.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.inventories.state</code>.
     */
    public void setState(State value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.inventories.state</code>.
     */
    public State getState() {
        return (State) get(4);
    }

    /**
     * Setter for <code>public.inventories.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.inventories.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.inventories.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.inventories.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.inventories.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.inventories.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, String, State, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, String, State, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Inventories.INVENTORIES.INVENTORY_ID;
    }

    @Override
    public Field<String> field2() {
        return Inventories.INVENTORIES.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Inventories.INVENTORIES.ACCOUNT_ID;
    }

    @Override
    public Field<String> field4() {
        return Inventories.INVENTORIES.DESCRIPTION;
    }

    @Override
    public Field<State> field5() {
        return Inventories.INVENTORIES.STATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Inventories.INVENTORIES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Inventories.INVENTORIES.LAST_UPDATED;
    }

    @Override
    public Field<Integer> field8() {
        return Inventories.INVENTORIES.TENANT_ID;
    }

    @Override
    public Integer component1() {
        return getInventoryId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAccountId();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public State component5() {
        return getState();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdated();
    }

    @Override
    public Integer component8() {
        return getTenantId();
    }

    @Override
    public Integer value1() {
        return getInventoryId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAccountId();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public State value5() {
        return getState();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdated();
    }

    @Override
    public Integer value8() {
        return getTenantId();
    }

    @Override
    public InventoriesRecord value1(Integer value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public InventoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public InventoriesRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public InventoriesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public InventoriesRecord value5(State value) {
        setState(value);
        return this;
    }

    @Override
    public InventoriesRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InventoriesRecord value7(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public InventoriesRecord value8(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public InventoriesRecord values(Integer value1, String value2, Integer value3, String value4, State value5, LocalDateTime value6, LocalDateTime value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoriesRecord
     */
    public InventoriesRecord() {
        super(Inventories.INVENTORIES);
    }

    /**
     * Create a detached, initialised InventoriesRecord
     */
    public InventoriesRecord(Integer inventoryId, String name, Integer accountId, String description, State state, LocalDateTime createdAt, LocalDateTime lastUpdated, Integer tenantId) {
        super(Inventories.INVENTORIES);

        setInventoryId(inventoryId);
        setName(name);
        setAccountId(accountId);
        setDescription(description);
        setState(state);
        setCreatedAt(createdAt);
        setLastUpdated(lastUpdated);
        setTenantId(tenantId);
        resetChangedOnNotNull();
    }
}
