/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.Items;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemsRecord extends UpdatableRecordImpl<ItemsRecord> implements Record8<Integer, Integer, String, Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.items.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.items.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.items.inventory_id</code>.
     */
    public void setInventoryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.items.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.items.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.items.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.items.threshold</code>.
     */
    public void setThreshold(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.items.threshold</code>.
     */
    public Integer getThreshold() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.items.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.items.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.items.sku</code>.
     */
    public void setSku(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.items.sku</code>.
     */
    public String getSku() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.items.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.items.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.items.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.items.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Items.ITEMS.ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Items.ITEMS.INVENTORY_ID;
    }

    @Override
    public Field<String> field3() {
        return Items.ITEMS.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Items.ITEMS.THRESHOLD;
    }

    @Override
    public Field<String> field5() {
        return Items.ITEMS.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return Items.ITEMS.SKU;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Items.ITEMS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Items.ITEMS.LAST_UPDATED;
    }

    @Override
    public Integer component1() {
        return getItemId();
    }

    @Override
    public Integer component2() {
        return getInventoryId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getThreshold();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getSku();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getLastUpdated();
    }

    @Override
    public Integer value1() {
        return getItemId();
    }

    @Override
    public Integer value2() {
        return getInventoryId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getThreshold();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getSku();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getLastUpdated();
    }

    @Override
    public ItemsRecord value1(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public ItemsRecord value2(Integer value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public ItemsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ItemsRecord value4(Integer value) {
        setThreshold(value);
        return this;
    }

    @Override
    public ItemsRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ItemsRecord value6(String value) {
        setSku(value);
        return this;
    }

    @Override
    public ItemsRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ItemsRecord value8(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public ItemsRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemsRecord
     */
    public ItemsRecord() {
        super(Items.ITEMS);
    }

    /**
     * Create a detached, initialised ItemsRecord
     */
    public ItemsRecord(Integer itemId, Integer inventoryId, String name, Integer threshold, String description, String sku, LocalDateTime createdAt, LocalDateTime lastUpdated) {
        super(Items.ITEMS);

        setItemId(itemId);
        setInventoryId(inventoryId);
        setName(name);
        setThreshold(threshold);
        setDescription(description);
        setSku(sku);
        setCreatedAt(createdAt);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
