/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.Orders;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record4<Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.orders.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.orders.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ORDER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Orders.ORDERS.TENANT_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Orders.ORDERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Orders.ORDERS.LAST_UPDATED;
    }

    @Override
    public Integer component1() {
        return getOrderId();
    }

    @Override
    public Integer component2() {
        return getTenantId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdated();
    }

    @Override
    public Integer value1() {
        return getOrderId();
    }

    @Override
    public Integer value2() {
        return getTenantId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdated();
    }

    @Override
    public OrdersRecord value1(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrdersRecord value2(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public OrdersRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OrdersRecord value4(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public OrdersRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer orderId, Integer tenantId, LocalDateTime createdAt, LocalDateTime lastUpdated) {
        super(Orders.ORDERS);

        setOrderId(orderId);
        setTenantId(tenantId);
        setCreatedAt(createdAt);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
