/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.OrderItems;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemsRecord extends UpdatableRecordImpl<OrderItemsRecord> implements Record3<Long, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_items.item_id</code>.
     */
    public void setItemId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_items.item_id</code>.
     */
    public String getItemId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OrderItems.ORDER_ITEMS.ORDER_ID;
    }

    @Override
    public Field<String> field2() {
        return OrderItems.ORDER_ITEMS.ITEM_ID;
    }

    @Override
    public Field<Integer> field3() {
        return OrderItems.ORDER_ITEMS.QUANTITY;
    }

    @Override
    public Long component1() {
        return getOrderId();
    }

    @Override
    public String component2() {
        return getItemId();
    }

    @Override
    public Integer component3() {
        return getQuantity();
    }

    @Override
    public Long value1() {
        return getOrderId();
    }

    @Override
    public String value2() {
        return getItemId();
    }

    @Override
    public Integer value3() {
        return getQuantity();
    }

    @Override
    public OrderItemsRecord value1(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrderItemsRecord value2(String value) {
        setItemId(value);
        return this;
    }

    @Override
    public OrderItemsRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OrderItemsRecord values(Long value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(Long orderId, String itemId, Integer quantity) {
        super(OrderItems.ORDER_ITEMS);

        setOrderId(orderId);
        setItemId(itemId);
        setQuantity(quantity);
        resetChangedOnNotNull();
    }
}
