/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.Suppliers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuppliersRecord extends UpdatableRecordImpl<SuppliersRecord> implements Record8<Integer, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.suppliers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.suppliers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.suppliers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.suppliers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.suppliers.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.suppliers.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.suppliers.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.suppliers.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.suppliers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.suppliers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.suppliers.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.suppliers.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.suppliers.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.suppliers.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.suppliers.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.suppliers.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Suppliers.SUPPLIERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Suppliers.SUPPLIERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Suppliers.SUPPLIERS.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Suppliers.SUPPLIERS.PHONE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Suppliers.SUPPLIERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Suppliers.SUPPLIERS.LAST_UPDATED;
    }

    @Override
    public Field<Integer> field7() {
        return Suppliers.SUPPLIERS.ACCOUNT_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Suppliers.SUPPLIERS.TENANT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdated();
    }

    @Override
    public Integer component7() {
        return getAccountId();
    }

    @Override
    public Integer component8() {
        return getTenantId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdated();
    }

    @Override
    public Integer value7() {
        return getAccountId();
    }

    @Override
    public Integer value8() {
        return getTenantId();
    }

    @Override
    public SuppliersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SuppliersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SuppliersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public SuppliersRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public SuppliersRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SuppliersRecord value6(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public SuppliersRecord value7(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public SuppliersRecord value8(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public SuppliersRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SuppliersRecord
     */
    public SuppliersRecord() {
        super(Suppliers.SUPPLIERS);
    }

    /**
     * Create a detached, initialised SuppliersRecord
     */
    public SuppliersRecord(Integer id, String name, String email, String phone, LocalDateTime createdAt, LocalDateTime lastUpdated, Integer accountId, Integer tenantId) {
        super(Suppliers.SUPPLIERS);

        setId(id);
        setName(name);
        setEmail(email);
        setPhone(phone);
        setCreatedAt(createdAt);
        setLastUpdated(lastUpdated);
        setAccountId(accountId);
        setTenantId(tenantId);
        resetChangedOnNotNull();
    }
}
