/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables.records;


import com.maelstrom.jooq.tables.SupplierItems;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierItemsRecord extends UpdatableRecordImpl<SupplierItemsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier_items.supplier_id</code>.
     */
    public void setSupplierId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier_items.supplier_id</code>.
     */
    public Integer getSupplierId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.supplier_items.item_id</code>.
     */
    public void setItemId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier_items.item_id</code>.
     */
    public String getItemId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SupplierItems.SUPPLIER_ITEMS.SUPPLIER_ID;
    }

    @Override
    public Field<String> field2() {
        return SupplierItems.SUPPLIER_ITEMS.ITEM_ID;
    }

    @Override
    public Integer component1() {
        return getSupplierId();
    }

    @Override
    public String component2() {
        return getItemId();
    }

    @Override
    public Integer value1() {
        return getSupplierId();
    }

    @Override
    public String value2() {
        return getItemId();
    }

    @Override
    public SupplierItemsRecord value1(Integer value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public SupplierItemsRecord value2(String value) {
        setItemId(value);
        return this;
    }

    @Override
    public SupplierItemsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierItemsRecord
     */
    public SupplierItemsRecord() {
        super(SupplierItems.SUPPLIER_ITEMS);
    }

    /**
     * Create a detached, initialised SupplierItemsRecord
     */
    public SupplierItemsRecord(Integer supplierId, String itemId) {
        super(SupplierItems.SUPPLIER_ITEMS);

        setSupplierId(supplierId);
        setItemId(itemId);
        resetChangedOnNotNull();
    }
}
