/*
 * This file is generated by jOOQ.
 */
package com.godelhaze.whitestone;


import com.godelhaze.whitestone.tables.Books;
import com.godelhaze.whitestone.tables.records.BooksRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BooksRecord> BOOKS_PKEY = Internal.createUniqueKey(Books.BOOKS, DSL.name("books_pkey"), new TableField[] { Books.BOOKS.BOOK_ID }, true);
    public static final UniqueKey<BooksRecord> BOOKS_TITLE_KEY = Internal.createUniqueKey(Books.BOOKS, DSL.name("books_title_key"), new TableField[] { Books.BOOKS.TITLE }, true);
}
