/*
 * This file is generated by jOOQ.
 */
package com.godelhaze.whitestone;


import com.godelhaze.whitestone.tables.Books;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;
}
