/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar;


import io.ceze.einar.tables.Locations;
import io.ceze.einar.tables.Profiles;
import io.ceze.einar.tables.Spaces;
import io.ceze.einar.tables.Tokens;
import io.ceze.einar.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.locations</code>.
     */
    public final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>public.profiles</code>.
     */
    public final Profiles PROFILES = Profiles.PROFILES;

    /**
     * The table <code>public.spaces</code>.
     */
    public final Spaces SPACES = Spaces.SPACES;

    /**
     * The table <code>public.tokens</code>.
     */
    public final Tokens TOKENS = Tokens.TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Locations.LOCATIONS,
            Profiles.PROFILES,
            Spaces.SPACES,
            Tokens.TOKENS,
            Users.USERS
        );
    }
}
