/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar;


import io.ceze.einar.tables.Addresses;
import io.ceze.einar.tables.Apartments;
import io.ceze.einar.tables.Negotiation;
import io.ceze.einar.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.addresses</code>.
     */
    public final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>public.apartments</code>.
     */
    public final Apartments APARTMENTS = Apartments.APARTMENTS;

    /**
     * The table <code>public.negotiation</code>.
     */
    public final Negotiation NEGOTIATION = Negotiation.NEGOTIATION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Addresses.ADDRESSES,
            Apartments.APARTMENTS,
            Negotiation.NEGOTIATION,
            Users.USERS
        );
    }
}
