/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar;


import io.ceze.einar.tables.Addresses;
import io.ceze.einar.tables.Apartments;
import io.ceze.einar.tables.Negotiation;
import io.ceze.einar.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.addresses</code>.
     */
    public static final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>public.apartments</code>.
     */
    public static final Apartments APARTMENTS = Apartments.APARTMENTS;

    /**
     * The table <code>public.negotiation</code>.
     */
    public static final Negotiation NEGOTIATION = Negotiation.NEGOTIATION;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
