/*
 * This file is generated by jOOQ.
 */
package io.ceze.einar;


import io.ceze.einar.tables.Profiles;
import io.ceze.einar.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.profiles</code>.
     */
    public static final Profiles PROFILES = Profiles.PROFILES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
