/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq;


import com.maelstrom.jooq.tables.Customers;
import com.maelstrom.jooq.tables.Inventories;
import com.maelstrom.jooq.tables.Items;
import com.maelstrom.jooq.tables.OrderItems;
import com.maelstrom.jooq.tables.Orders;
import com.maelstrom.jooq.tables.records.CustomersRecord;
import com.maelstrom.jooq.tables.records.InventoriesRecord;
import com.maelstrom.jooq.tables.records.ItemsRecord;
import com.maelstrom.jooq.tables.records.OrderItemsRecord;
import com.maelstrom.jooq.tables.records.OrdersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> CUSTOMERS_EMAIL_KEY = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("customers_email_key"), new TableField[] { Customers.CUSTOMERS.EMAIL }, true);
    public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("customers_pkey"), new TableField[] { Customers.CUSTOMERS.CUSTOMER_ID }, true);
    public static final UniqueKey<InventoriesRecord> INVENTORIES_PKEY = Internal.createUniqueKey(Inventories.INVENTORIES, DSL.name("inventories_pkey"), new TableField[] { Inventories.INVENTORIES.INVENTORY_ID }, true);
    public static final UniqueKey<InventoriesRecord> INVENTORIES_TENANT_ID_NAME_KEY = Internal.createUniqueKey(Inventories.INVENTORIES, DSL.name("inventories_tenant_id_name_key"), new TableField[] { Inventories.INVENTORIES.TENANT_ID, Inventories.INVENTORIES.NAME }, true);
    public static final UniqueKey<ItemsRecord> ITEMS_INVENTORY_ID_NAME_KEY = Internal.createUniqueKey(Items.ITEMS, DSL.name("items_inventory_id_name_key"), new TableField[] { Items.ITEMS.INVENTORY_ID, Items.ITEMS.NAME }, true);
    public static final UniqueKey<ItemsRecord> ITEMS_NAME_KEY = Internal.createUniqueKey(Items.ITEMS, DSL.name("items_name_key"), new TableField[] { Items.ITEMS.NAME }, true);
    public static final UniqueKey<ItemsRecord> ITEMS_PKEY = Internal.createUniqueKey(Items.ITEMS, DSL.name("items_pkey"), new TableField[] { Items.ITEMS.ITEM_ID }, true);
    public static final UniqueKey<ItemsRecord> ITEMS_SKU_KEY = Internal.createUniqueKey(Items.ITEMS, DSL.name("items_sku_key"), new TableField[] { Items.ITEMS.SKU }, true);
    public static final UniqueKey<OrderItemsRecord> ORDER_ITEMS_PKEY = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_pkey"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID, OrderItems.ORDER_ITEMS.ITEM_ID }, true);
    public static final UniqueKey<OrdersRecord> ORDERS_PKEY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("orders_pkey"), new TableField[] { Orders.ORDERS.ORDER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ItemsRecord, InventoriesRecord> ITEMS__FK_INVENTORY = Internal.createForeignKey(Items.ITEMS, DSL.name("fk_inventory"), new TableField[] { Items.ITEMS.INVENTORY_ID }, Keys.INVENTORIES_PKEY, new TableField[] { Inventories.INVENTORIES.INVENTORY_ID }, true);
    public static final ForeignKey<OrderItemsRecord, ItemsRecord> ORDER_ITEMS__FK_ITEM = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_item"), new TableField[] { OrderItems.ORDER_ITEMS.ITEM_ID }, Keys.ITEMS_SKU_KEY, new TableField[] { Items.ITEMS.SKU }, true);
    public static final ForeignKey<OrderItemsRecord, OrdersRecord> ORDER_ITEMS__FK_ORDER = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_order"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, Keys.ORDERS_PKEY, new TableField[] { Orders.ORDERS.ORDER_ID }, true);
}
