/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq;


import com.maelstrom.jooq.tables.Accounts;
import com.maelstrom.jooq.tables.Inventories;
import com.maelstrom.jooq.tables.Items;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.inventories</code>.
     */
    public final Inventories INVENTORIES = Inventories.INVENTORIES;

    /**
     * The table <code>public.items</code>.
     */
    public final Items ITEMS = Items.ITEMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accounts.ACCOUNTS,
            Inventories.INVENTORIES,
            Items.ITEMS
        );
    }
}
