/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq;


import com.maelstrom.jooq.tables.Customers;
import com.maelstrom.jooq.tables.Inventories;
import com.maelstrom.jooq.tables.Items;
import com.maelstrom.jooq.tables.OrderItems;
import com.maelstrom.jooq.tables.Orders;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.inventories</code>.
     */
    public static final Inventories INVENTORIES = Inventories.INVENTORIES;

    /**
     * The table <code>public.items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;
}
