/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq;


import com.maelstrom.jooq.tables.Inventories;
import com.maelstrom.jooq.tables.Items;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.inventories</code>.
     */
    public static final Inventories INVENTORIES = Inventories.INVENTORIES;

    /**
     * The table <code>public.items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;
}
