/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables;


import com.maelstrom.jooq.Keys;
import com.maelstrom.jooq.Public;
import com.maelstrom.jooq.enums.State;
import com.maelstrom.jooq.tables.records.InventoriesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventories extends TableImpl<InventoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.inventories</code>
     */
    public static final Inventories INVENTORIES = new Inventories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoriesRecord> getRecordType() {
        return InventoriesRecord.class;
    }

    /**
     * The column <code>public.inventories.inventory_id</code>.
     */
    public final TableField<InventoriesRecord, Integer> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.inventories.account_id</code>.
     */
    public final TableField<InventoriesRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.inventories.name</code>.
     */
    public final TableField<InventoriesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.inventories.description</code>.
     */
    public final TableField<InventoriesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.inventories.state</code>.
     */
    public final TableField<InventoriesRecord, State> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'OPEN'::state"), SQLDataType.VARCHAR)).asEnumDataType(com.maelstrom.jooq.enums.State.class), this, "");

    /**
     * The column <code>public.inventories.created_at</code>.
     */
    public final TableField<InventoriesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.inventories.last_updated</code>.
     */
    public final TableField<InventoriesRecord, LocalDateTime> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.inventories.tenant_id</code>.
     */
    public final TableField<InventoriesRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Inventories(Name alias, Table<InventoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Inventories(Name alias, Table<InventoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.inventories</code> table reference
     */
    public Inventories(String alias) {
        this(DSL.name(alias), INVENTORIES);
    }

    /**
     * Create an aliased <code>public.inventories</code> table reference
     */
    public Inventories(Name alias) {
        this(alias, INVENTORIES);
    }

    /**
     * Create a <code>public.inventories</code> table reference
     */
    public Inventories() {
        this(DSL.name("inventories"), null);
    }

    public <O extends Record> Inventories(Table<O> child, ForeignKey<O, InventoriesRecord> key) {
        super(child, key, INVENTORIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InventoriesRecord, Integer> getIdentity() {
        return (Identity<InventoriesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InventoriesRecord> getPrimaryKey() {
        return Keys.INVENTORIES_PKEY;
    }

    @Override
    public List<UniqueKey<InventoriesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.INVENTORIES_ACCOUNT_ID_NAME_KEY);
    }

    @Override
    public List<ForeignKey<InventoriesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVENTORIES__FK_ACCOUNT);
    }

    private transient Accounts _accounts;

    /**
     * Get the implicit join path to the <code>public.accounts</code> table.
     */
    public Accounts accounts() {
        if (_accounts == null)
            _accounts = new Accounts(this, Keys.INVENTORIES__FK_ACCOUNT);

        return _accounts;
    }

    @Override
    public Inventories as(String alias) {
        return new Inventories(DSL.name(alias), this);
    }

    @Override
    public Inventories as(Name alias) {
        return new Inventories(alias, this);
    }

    @Override
    public Inventories as(Table<?> alias) {
        return new Inventories(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventories rename(String name) {
        return new Inventories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventories rename(Name name) {
        return new Inventories(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventories rename(Table<?> name) {
        return new Inventories(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, State, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Integer, ? super Integer, ? super String, ? super String, ? super State, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Integer, ? super Integer, ? super String, ? super String, ? super State, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
