/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables;


import com.maelstrom.jooq.Keys;
import com.maelstrom.jooq.Public;
import com.maelstrom.jooq.tables.records.ItemsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Items extends TableImpl<ItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.items</code>
     */
    public static final Items ITEMS = new Items();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemsRecord> getRecordType() {
        return ItemsRecord.class;
    }

    /**
     * The column <code>public.items.item_id</code>.
     */
    public final TableField<ItemsRecord, Integer> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.items.inventory_id</code>.
     */
    public final TableField<ItemsRecord, Integer> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.items.name</code>.
     */
    public final TableField<ItemsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.items.description</code>.
     */
    public final TableField<ItemsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.items.sku</code>.
     */
    public final TableField<ItemsRecord, String> SKU = createField(DSL.name("sku"), SQLDataType.VARCHAR(12).nullable(false), this, "");

    /**
     * The column <code>public.items.bmax</code>.
     */
    public final TableField<ItemsRecord, Integer> BMAX = createField(DSL.name("bmax"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.items.bmin</code>.
     */
    public final TableField<ItemsRecord, Integer> BMIN = createField(DSL.name("bmin"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.items.created_at</code>.
     */
    public final TableField<ItemsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.items.last_updated</code>.
     */
    public final TableField<ItemsRecord, LocalDateTime> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private Items(Name alias, Table<ItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Items(Name alias, Table<ItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.items</code> table reference
     */
    public Items(String alias) {
        this(DSL.name(alias), ITEMS);
    }

    /**
     * Create an aliased <code>public.items</code> table reference
     */
    public Items(Name alias) {
        this(alias, ITEMS);
    }

    /**
     * Create a <code>public.items</code> table reference
     */
    public Items() {
        this(DSL.name("items"), null);
    }

    public <O extends Record> Items(Table<O> child, ForeignKey<O, ItemsRecord> key) {
        super(child, key, ITEMS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ItemsRecord, Integer> getIdentity() {
        return (Identity<ItemsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ItemsRecord> getPrimaryKey() {
        return Keys.ITEMS_PKEY;
    }

    @Override
    public List<UniqueKey<ItemsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ITEMS_INVENTORY_ID_NAME_KEY, Keys.ITEMS_NAME_KEY, Keys.ITEMS_SKU_KEY);
    }

    @Override
    public List<ForeignKey<ItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEMS__FK_INVENTORY);
    }

    private transient Inventories _inventories;

    /**
     * Get the implicit join path to the <code>public.inventories</code> table.
     */
    public Inventories inventories() {
        if (_inventories == null)
            _inventories = new Inventories(this, Keys.ITEMS__FK_INVENTORY);

        return _inventories;
    }

    @Override
    public Items as(String alias) {
        return new Items(DSL.name(alias), this);
    }

    @Override
    public Items as(Name alias) {
        return new Items(alias, this);
    }

    @Override
    public Items as(Table<?> alias) {
        return new Items(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(String name) {
        return new Items(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(Name name) {
        return new Items(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(Table<?> name) {
        return new Items(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
