/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables;


import com.maelstrom.jooq.Keys;
import com.maelstrom.jooq.Public;
import com.maelstrom.jooq.tables.records.SupplierItemsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierItems extends TableImpl<SupplierItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier_items</code>
     */
    public static final SupplierItems SUPPLIER_ITEMS = new SupplierItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierItemsRecord> getRecordType() {
        return SupplierItemsRecord.class;
    }

    /**
     * The column <code>public.supplier_items.supplier_id</code>.
     */
    public final TableField<SupplierItemsRecord, Integer> SUPPLIER_ID = createField(DSL.name("supplier_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_items.item_id</code>.
     */
    public final TableField<SupplierItemsRecord, String> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.VARCHAR(12).nullable(false), this, "");

    private SupplierItems(Name alias, Table<SupplierItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupplierItems(Name alias, Table<SupplierItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier_items</code> table reference
     */
    public SupplierItems(String alias) {
        this(DSL.name(alias), SUPPLIER_ITEMS);
    }

    /**
     * Create an aliased <code>public.supplier_items</code> table reference
     */
    public SupplierItems(Name alias) {
        this(alias, SUPPLIER_ITEMS);
    }

    /**
     * Create a <code>public.supplier_items</code> table reference
     */
    public SupplierItems() {
        this(DSL.name("supplier_items"), null);
    }

    public <O extends Record> SupplierItems(Table<O> child, ForeignKey<O, SupplierItemsRecord> key) {
        super(child, key, SUPPLIER_ITEMS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SupplierItemsRecord> getPrimaryKey() {
        return Keys.SUPPLIER_ITEMS_PKEY;
    }

    @Override
    public List<ForeignKey<SupplierItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SUPPLIER_ITEMS__FK_SUPPLIER, Keys.SUPPLIER_ITEMS__FK_ITEM);
    }

    private transient Suppliers _suppliers;
    private transient Items _items;

    /**
     * Get the implicit join path to the <code>public.suppliers</code> table.
     */
    public Suppliers suppliers() {
        if (_suppliers == null)
            _suppliers = new Suppliers(this, Keys.SUPPLIER_ITEMS__FK_SUPPLIER);

        return _suppliers;
    }

    /**
     * Get the implicit join path to the <code>public.items</code> table.
     */
    public Items items() {
        if (_items == null)
            _items = new Items(this, Keys.SUPPLIER_ITEMS__FK_ITEM);

        return _items;
    }

    @Override
    public SupplierItems as(String alias) {
        return new SupplierItems(DSL.name(alias), this);
    }

    @Override
    public SupplierItems as(Name alias) {
        return new SupplierItems(alias, this);
    }

    @Override
    public SupplierItems as(Table<?> alias) {
        return new SupplierItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierItems rename(String name) {
        return new SupplierItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierItems rename(Name name) {
        return new SupplierItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierItems rename(Table<?> name) {
        return new SupplierItems(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
