/*
 * This file is generated by jOOQ.
 */
package com.maelstrom.jooq.tables;


import com.maelstrom.jooq.Keys;
import com.maelstrom.jooq.Public;
import com.maelstrom.jooq.tables.records.SuppliersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Suppliers extends TableImpl<SuppliersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.suppliers</code>
     */
    public static final Suppliers SUPPLIERS = new Suppliers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SuppliersRecord> getRecordType() {
        return SuppliersRecord.class;
    }

    /**
     * The column <code>public.suppliers.id</code>.
     */
    public final TableField<SuppliersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.suppliers.name</code>.
     */
    public final TableField<SuppliersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.suppliers.email</code>.
     */
    public final TableField<SuppliersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.suppliers.phone</code>.
     */
    public final TableField<SuppliersRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.suppliers.created_at</code>.
     */
    public final TableField<SuppliersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.suppliers.last_updated</code>.
     */
    public final TableField<SuppliersRecord, LocalDateTime> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.suppliers.account_id</code>.
     */
    public final TableField<SuppliersRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.suppliers.tenant_id</code>.
     */
    public final TableField<SuppliersRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Suppliers(Name alias, Table<SuppliersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Suppliers(Name alias, Table<SuppliersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.suppliers</code> table reference
     */
    public Suppliers(String alias) {
        this(DSL.name(alias), SUPPLIERS);
    }

    /**
     * Create an aliased <code>public.suppliers</code> table reference
     */
    public Suppliers(Name alias) {
        this(alias, SUPPLIERS);
    }

    /**
     * Create a <code>public.suppliers</code> table reference
     */
    public Suppliers() {
        this(DSL.name("suppliers"), null);
    }

    public <O extends Record> Suppliers(Table<O> child, ForeignKey<O, SuppliersRecord> key) {
        super(child, key, SUPPLIERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SuppliersRecord, Integer> getIdentity() {
        return (Identity<SuppliersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SuppliersRecord> getPrimaryKey() {
        return Keys.SUPPLIERS_PKEY;
    }

    @Override
    public List<UniqueKey<SuppliersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SUPPLIERS_ACCOUNT_ID_EMAIL_KEY);
    }

    @Override
    public Suppliers as(String alias) {
        return new Suppliers(DSL.name(alias), this);
    }

    @Override
    public Suppliers as(Name alias) {
        return new Suppliers(alias, this);
    }

    @Override
    public Suppliers as(Table<?> alias) {
        return new Suppliers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Suppliers rename(String name) {
        return new Suppliers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Suppliers rename(Name name) {
        return new Suppliers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Suppliers rename(Table<?> name) {
        return new Suppliers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
